name: nimcube
version: '0.0.0'
main: com.timur.nimcube.Nimcube
api-version: '1.21'
load: STARTUP
authors: [ Ruskei ]
description: Library for reducing packets for display entities

commands:
  nim_greedy_test:
  nim_cuboid:
  nim_portal:
  nim_grid_cuboids:
  nim_clear:
  nim_clear_portals:
  nim_freeze:
  nim_step:
